server:
  port: 8080

spring:
  application:
    name: user-api-gateway
  cloud:
    gateway:
      routes:
        - id: user-auth
          uri: lb://USER-AUTH
          predicates:
            - Path=/auth/**

        - id: user-account
          uri: lb://USER-ACCOUNT
          predicates:
            - Path=/account/**

        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/orders/**

        - id: products-service
          uri: lb://PRODUCTS-SERVICE
          predicates:
            - Path=/products/**, /product_stock/**
      discovery:
        locator:
          enabled: true
          lsower-case-service-id: true
management:
  endpoints:
    web:
      exposure:
        include: health,info, prometheus

eureka:
  instance:
    prefer-ip-address: true
    hostname: eureka
  client:
    service-url:
      defaultZone: http://${EUREKA_INSTANCE_HOSTNAME}:${EUREKA_SERVER_PORT}/eureka
    register-with-eureka: true
    fetch-registry: true

secret:
  key: ${JWT_SECRET:5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437}
