server:
  port: 8080

spring:
  application:
    name: user-api-gateway
  cloud:
    gateway:
      routes:
        - id: user-auth
          uri: lb://USER-AUTH
          predicates:
            - Path=/auth/**

        - id: user-account
          uri: lb://USER-ACCOUNT
          predicates:
            - Path=/account/**
          filters:
            - AuthenticationFilter
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true